### ISSUE TITLE
binance-coinbase-listing-predictor does not work

### ISSUE THREAD

**Issue by I7y3o1** [brianleect/binance-coinbase-listing-predictor#10]
Installed all add-ons. I tied the telegram bot, but, unfortunately, I don’t receive any data. Neither in telegrams, nor in the console. What am I doing wrong?

![image_2022-05-23_23-36-23](https://user-images.githubusercontent.com/106140747/169967899-50656f03-ddb9-44fa-8ea0-a24e0ce1a8dd.png)

**Comment by brianleect** [comment]
@I7y3o1 Try the newest version. I made the column dropping more generic. Should work now. One thing to note is that the previous version worked on my local environment before the changes as well.
